### ISSUE TITLE
[feat]is there a plan to support generator?

### ISSUE THREAD

**Issue by liunux4odoo** [Nanguage/executor-engine#3]
* Executor version: 0.2.5
* Python version: 3.10
* Operating System: win10

### Description

Running generator as job raises pickle error.

### What I Did
```
from executor.engine import Engine, ProcessJob


def f():
    import time
    for i in range(3):
        time.sleep(1)
        yield i


with Engine() as engine:
    job = ProcessJob(f)
    engine.submit(job)
    engine.wait()
    print(job.result())
```
```

**Comment by Nanguage** [comment]
This feature is not supported at the moment, but I will think about how to support it.

**Comment by Nanguage** [comment]
The new release [`0.2.6`](https://github.com/Nanguage/executor-engine/releases/tag/0.2.6) has supported this feature,  it has been uploaded to the [PyPI](https://pypi.org/project/executor-engine/0.2.6/).

**Comment by Nanguage** [comment]
The `send` method for the generator is supported in the new release [`0.2.7`](https://github.com/Nanguage/executor-engine/releases/tag/0.2.7), this feature can be used for pass data to the generator, it allow executor communicate with another thread/process:

```python
import asyncio
from executor.engine import Engine, ProcessJob

def calculator():
    res = None
    while True:
        expr = yield res
        res = eval(expr)


async def main():
    with Engine() as engine:
        job = ProcessJob(calculator)
        await engine.submit_async(job)
        await job.wait_until_status("running")
        g = job.result()
        g.send(None)  # initialize the generator
        print(g.send("1 + 2"))  # 3
        print(g.send("3 * 4"))  # 12
        print(g.send("(1 + 2) * 4"))  # 12

asyncio.run(main())
```

see https://github.com/Nanguage/executor-engine/commit/669d71f06254f19ffe402f3d71df0a92f0dc826c
